### PR TITLE
Added SearchPanes documentation

### PR DESCRIPTION
**Pull request by Arne1303**
Added SearchPanes documentation!

The setup and simple use is documented, there is this one comment (https://github.com/yajra/laravel-datatables/issues/2463#issuecomment-729455147) in which you talk about adding a column definition but I'm not sure why and when that is needed so I haven't documented that one for now.

Refs:
 - yajra/laravel-datatables#2475
 - yajra/laravel-datatables#2463

### CODE REVIEW

**Comment by yajra** [comment]
Thanks a lot! Appreciate the support in docs

**Comment by markplus** [comment]
Hello, I don't understand why I can't use searchPanes with serverside, it remains blank, empty, I've been looking for a solution for days but I can't find it, I also bought the datatables editor but I can't get it to work, can anyone help me figure out how to solve this problem?

**Comment by Arne1303** [comment]
@markplus :/ Sadly, Blank SearchPanes are sometimes just the behavior when something is wrong, in some cases there are no exceptions being thrown which makes debugging them really difficult. 

The "Warning" you are getting indicates that something went wrong while processing the PHP code, you can open the developer console in the browser (F12) and go to the network tab. When you then reload the Page, you should see all the requests being made which includes the failing one. You can then click on the failing request and see the exception message in the "response" part.

**Comment by markplus** [comment]
thanks for the answer, I also bought the datatables editor, but I still can't get it to work in any way, if I don't use serverside everything works perfectly, but the problem is that I have tables with a lot of data and I have to use serverside, now after the many tests I'm doing I've come to this code, I use laravel

controller
`    public function index(Request $request)
    {
        Session::put('page','tickets');

        $db = Ticket::select('*');

        Editor::inst($db)
        ->fields(
            Field::inst('id')->searchPaneOptions( SearchPaneOptions::inst()),
            Field::inst('stato')->searchPaneOptions( SearchPaneOptions::inst()),
            Field::inst('segnalazione')->searchPaneOptions( SearchPaneOptions::inst()),
            Field::inst('orario')->searchPaneOptions( SearchPaneOptions::inst()),
            Field::inst('priorita')->searchPaneOptions( SearchPaneOptions::inst()),
            Field::inst('chiusura')->searchPaneOptions( SearchPaneOptions::inst()),
            Field::inst('descrizione')->searchPaneOptions( SearchPaneOptions::inst()),
            Field::inst('categoria')->searchPaneOptions( SearchPaneOptions::inst()),
        );

        if ($request->ajax()) {
            $data = Ticket::select('*');
            return DataTables::of($data)
            ->addIndexColumn()
                ->addColumn('action', function($row){
                    $btn  = '<a href="'.route('tickets.show', $row->id).'"><i class="ti-eye"></i></a>
                            <a href="'.route('tickets.edit', $row->id).'"><i class="ti-pencil"></i></a>
                            <a href="'.route('tickets.create', $row->id).'"><i class="icon-plus"></i></a>';
                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }

        return view('tickets.index');
    }`

index.blade.php

`@push('scripts')
    <script type="text/javascript">
        const editor = new DataTable.Editor({
            ajax: '{{ route('tickets.index') }}',
            fields: [
                {label: 'Ticket', name: 'id'},
                {label: 'Stato', name:'stato'},
                {label: 'Segnalazione', name: 'segnalazione'},
                {label: 'Orario', name: 'orario'},
                {label: 'Priorita', name: 'priorita'},
                {label: 'Chiusura', name: 'chiusura'},
                {label: 'Descrizione', name: 'descrizione'},
                {label: 'Categoria', name: 'categoria'},
            ],
            table: 'table.display'
        });
        new DataTable('table.display', {
            language: {
                url: "//cdn.datatables.net/plug-ins/1.13.5/i18n/it-IT.json"
            },
            ajax:'{{ route('tickets.index') }}',
            dataType:"json",
            type: "POST",
                
            buttons: [
                { extend: 'create', editor },
                { extend: 'edit', editor },
                { extend: 'remove', editor },
                { extend: 'copyHtml5', text: 'Copia', titleAttr: 'Copia', className: 'btn'}, 
                { extend: 'csvHtml5', text: 'CSV', titleAttr: 'CSV', className: 'btn'}, 
                { extend: 'excelHtml5',text: 'Excel',titleAttr: 'Excel',className: 'btn'}, 
                { extend: 'pdfHtml5',orientation: 'landscape',pageSize: 'LEGAL',text: 'PDF',titleAttr: 'PDF', className: 'btn'}, 
                { extend: 'print',text: 'Stampa',titleAttr: 'Stampa',className: 'btn'},
                { extend: "colvis", postfixButtons: ["colvisRestore"]},
            ],
            columns: [
                {data: 'id', name: 'id'},
                {data: 'stato', name: 'stato'},
                {data: 'segnalazione', name: 'segnalazione'},
                {data: 'orario', name: 'orario'},
                {data: 'priorita', name: 'priorita'},
                {data: 'chiusura', name: 'chiusura'},
                {data: 'descrizione', name: 'descrizione'},
                {data: 'categoria', name: 'categoria'},
            ],
            dom: '<PBfrt<t>lip>',
            deferRender: true,
            responsive: true,
            lengthChange: true,
            orderCellsTop: true,
            fixedHeader: true,
            select: true,
            processing: true,
            serverSide: true,
            stateSave: true,
            searchPanes:{
                cascadePanes: true,
                initCollapsed: true,
                show: true,
                dtOpts:{
                    dom: 'tp',
                    paging: 'true',
                    pagingType: 'simple',
                    searching: true
                }
            },
            columnDefs: [
                {
                    target: 2,
                    render: DataTable.render.date(),
                    target: 5,
                    render: DataTable.render.ellipsis( 17, true ),
                    searchPanes: {
                        show: true
                    },
                    targets: '_all',
                }
            ],
        });
    </script>
@endpush`

**Comment by markplus** [comment]
I display the tiles correctly, everything seems to work but there are no values in the tiles

```
<?php

namespace App\DataTables;

use App\Models\Ticket;
use Illuminate\Database\Eloquent\Builder as QueryBuilder;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\EloquentDataTable;
use Yajra\DataTables\Facades\DataTables;
use Yajra\DataTables\Html\Builder as HtmlBuilder;
use Yajra\DataTables\Html\Button;
use Yajra\DataTables\Html\Column;
use Yajra\DataTables\Html\Editor\Editor;
use Yajra\DataTables\Html\Editor\Fields;
use Yajra\DataTables\Html\SearchPane;
use Yajra\DataTables\Services\DataTable;
use Yajra\DataTables\Html\ColumnDefinition;

class TicketsDataTable extends DataTable
{
    /**
     * Build the DataTable class.
     *
     * @param QueryBuilder $query Results from query() method.
     */
    public function dataTable(QueryBuilder $query): EloquentDataTable
    {

        return (new EloquentDataTable($query))->setRowId('id');

    }

    /**
     * Get the query source of dataTable.
     */
    public function query(Ticket $model): QueryBuilder
    {
        return $model->newQuery();
    }

    /**
     * Optional method if you want to use the html builder.
     */
    public function html(): HtmlBuilder
    {
        return $this->builder()
                    ->setTableId('tickets-table')
                    ->columns($this->getColumns())
                    ->addColumnDef([
                        'searchPanes' => ['show' => true],
                        'targets' => ['_all'],
                    ])
                    ->minifiedAjax()
                    ->orderBy(1)
                    ->selectStyleSingle()
                    ->serverSide(true)
                    ->processing(true)
                    ->stateSave(true)
                    ->select(true)
                    ->fixedHeader(true)
                    ->deferRender(true)
                    ->orderCellsTop(true)
                    ->lengthChange(true)
                    ->autoWidth(false)
                    ->responsive(true)
                    ->searchPanes(true)
                    ->editors([
                        Editor::make()
                              ->fields([
                                Fields\Text::make('id'),
                                Fields\Text::make('tipo'),
                                Fields\Text::make('stato'),
                                Fields\Text::make('segnalazione'),
                                Fields\Text::make('priorita'),
                                Fields\Text::make('chiusura'),
                                Fields\Text::make('categoria'),
                              ]),
                    ])
                    ->buttons([
                        Button::make('create')->editor('editor'),
                        Button::make('edit')->editor('editor'),
                        Button::make('remove')->editor('editor'),
                        Button::make('excel'),
                        Button::make('csv'),
                        Button::make('pdf'),
                        Button::make('print'),
                        Button::make('reset'),
                        Button::make('reload')
                    ])
                    ->parameters([
                        'dom' => '<PBfrt<t>lip>',
                        'language' => ['url' => url('vendors/it-IT.json')],
                    ]);
    }

    /**
     * Get the dataTable columns definition.
     */
    public function getColumns(): array
    {
        return [
            Column::make('id'),
            Column::make('tipo'),
            Column::make('stato'),
            Column::make('segnalazione'),
            Column::make('priorita'),
            Column::make('chiusura'),
            Column::make('categoria'),
        ];
    }

    /**
     * Get the filename for export.
     */
    protected function filename(): string
    {
        return 'Tickets_' . date('YmdHis');
    }
}
```

- PHP v8.2.5
- Laravel v10.17.0

**Comment by markplus** [comment]
Can anyone tell me where the error is? I can't understand why the result isn't grouped and I see it individually, where am I going wrong?
```

        ->searchPane(

            'categoria',

            fn() => Ticket::query()->whereYear('created_at', '2023') ->whereMonth('created_at','08')
           ->select('categoria value', 'categoria as label')->get(),

            function (\Illuminate\Database\Eloquent\Builder $query, array $values) {
                return $query
                    ->whereIn(
                        'categoria',
                        $values);
            }
            
        )
```
[](https://postimg.cc/kV9cpSc3)

**Comment by yajra** [comment]
It seems like the behavior of searchPanes changed since the last time I checked. I was able to test this today and this is the config that works for me.

```php
            ->searchPanes(SearchPane::make())
            //->searchPanes(SearchPane::make()->columns([1,2,...])) add columns to display specific index
            ->addColumnDef([
                'targets' => '_all',
                'searchPanes' => [
                    'show' => true,
                    'vieTotal' => false,
                    'viewCount' => false,
                ],
            ])
```

Will update the docs, Thanks!

**Comment by yajra** [comment]
Note: I just noticed that when using searchPanes button, columnDef must be used instead for it to work. Will patch and review the docs soon. Thanks!

```php
            ->addColumnDef([
                'targets' => '_all',
                'searchPanes' => [
                    'show' => true,
                ],
            ])
            ->buttons([Button::make('searchPanes')]
```

**Pull request merged**
